[package]
name = "websockets"
version = "0.1.0"
edition = "2021"


[dependencies]
tungstenite = { version = "0.20", features = ["native-tls"]}
url = "2.2"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"
